### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by ivanhercaz**
Hi everyone!

Finally, I finished the translation to Spanish. I reviewed it several times to be sure of the correct grammar and spelling. I have some "silly" doubts, but nothing incorrect, only about if it is better to say which one or another word, but the meaning is the same. Here you have some notes about this translation:
* This translation **is not adapted to the law of Spain**. I have to research about the law, but I need time and help of an specialist in the copyright law of Spain. I kept the examples of the Germany law, because it is the best way to clarify the reasons to the users that they are who has the responsibility to confirm the legal viability of the licenses in their respective countries.
* In Spanish we have (more than) two ways to refer to the second person: "tú", and "usted" There isn't an specific rule to use one or another, because in some regions of Spain is used one or another, as long in some countries of Latin America is used one or another, or even the "vos". It is complicated, but you have [this link](http://www.fundeu.es/consulta/tu-vos-usted-49/) to check what I am talking about (unfortunately is in Spanish, if you want, I can translate it for you, because is little). I preferred to use "tú" to be nearest to the general speakers. In Spain, generally, the use of "usted" is more formal than "tú". If you think that the text in Spanish have to be more formal than colloquial, I can change it without problems.

I'm going to comment this two things in the [Commons talk](https://commons.wikimedia.org/wiki/Commons_talk:Attribution_Generator), maybe is better to talk about it there. But, any doubt about the pull request, preferably here, no?

I think that I'm not forgetting anything so... pull requested created!

Regards, Ivanhercaz

### CODE REVIEW

**Comment by tobijat** [comment]
Looks good to me, tested it locally and texts seem fine (though don't understand Spanish :) ). @jakobw @manicki wondering if you spot any issue, if not we can just merge this and deploy it.

**Comment by jakobw** [comment]
The line break on the "next" button is a little awkward, but other than that it looks good!
screen shot 2017-09-06 at 16 56 29

Will merge and deploy in a bit unless someone shouts :)

**Comment by jakobw** [comment]
Ah, never mind the comment about the line break. I just realized it always does that when the window is too narrow - just a little sooner with the Spanish one because "Siguiente" is slightly longer than "Weiter" or "Next" :)

Talked to @manicki and will deploy it now!

**Comment by manicki** [comment]
@ivanhercaz: Very coool, thank you!

**Comment by jakobw** [comment]
Deployed!
https://lizenzhinweisgenerator.de/?lang=es
Thanks @ivanhercaz!

**Pull request merged**
