### PR TITLE
Replacing the article that preceed the word "repositorio"

### PR DESCRIPTION
**Pull request by ivanhercaz**
Hi everyone!

I replace the article "la" to "el" when it is preceding the word "repositorio" because the this word in Spanish [is a masculine noun](http://dle.rae.es/?id=OkMvGE8), not female.

Regards, Iván

### CODE REVIEW

**Comment by manicki** [comment]
Thanks @ivanhercaz! So https://github.com/wmde/Lizenzhinweisgenerator/pull/255/commits/a75bb40c1e96cb24db2b09a769edf81fcbfc4360 is the only change to submitted this time, right? Github shows weirdly 10 more commits. We wouldn't like to get extra stuff to the version history but the relevant commit only.
I will try to fix the PR later today and include only https://github.com/wmde/Lizenzhinweisgenerator/pull/255/commits/a75bb40c1e96cb24db2b09a769edf81fcbfc4360

**Comment by tobijat** [comment]
fixed merge conflict. @manicki do you still want to cherry-pick that one commit, or should we just merge it?

**Comment by manicki** [comment]
will cherry pick in a second

**Comment by manicki** [comment]
submitted as https://github.com/wmde/Lizenzhinweisgenerator/pull/257. Didn't want to mess with the master of Ivan's fork.

**Comment by ivanhercaz** [comment]
You're welcome @manicki! At first, yes, it is the only commit. But if you want I can make another commit because I have read again the text and I had a coherence error. I mean that I wrote "de _el_ repositorio". When there is a "de", a preposition, before a "el", an article, it could be written as "del". What do you think? Should I make another commit?

One doubt that I have. I don't understand why if I update my fork from your master repository before work in it, then I made the pull request and it add my previous commits that I already add to your master with another pull request.

Thanks in advance with your help!

**Comment by ivanhercaz** [comment]
Well, I have notice that @manicki accept my commit in another branch called "repositorio" and then merged it in the master branch. So I am going to wait to your comments before make anything more.

I await your answer!

**Comment by manicki** [comment]
@ivanhercaz good point, I believe it makes sense to have "de el" changed to "del".

Regarding working with the fork, I believe the problem is that your fork and our repo have diverged. Namely, "your" master branch has some commits in it which haven't been included in the pull request with the Spanish translation.
When I compare master branches of two repos (https://github.com/wmde/Lizenzhinweisgenerator/compare/master...ivanhercaz:master), I can see e.g. commits from https://github.com/ivanhercaz/Lizenzhinweisgenerator/commit/04e6c97609f39a10ab5f28108506ac331335f4de to https://github.com/wmde/Lizenzhinweisgenerator/commit/c00523b83d7a2d18596ea64987eb2ffabff55955, which your master has, and "our" does not.
Looking at the PR (https://github.com/wmde/Lizenzhinweisgenerator/pull/248) I believe the cause of the "issue" is that we didn't merge all of your commits to master, but instead, we have squashed them into a single commit https://github.com/wmde/Lizenzhinweisgenerator/commit/00b346d9a99e9baf10cbc971c769b5ce454fcbae which we merged to wmde master.
Your master before the pull request didn't have https://github.com/wmde/Lizenzhinweisgenerator/commit/00b346d9a99e9baf10cbc971c769b5ce454fcbae which was then added when you have merged our master to your fork. Git does not what were commits 00b346d9a99e9baf10cbc971c769b5ce454fcbae has been created from, for git these are completely separate commits.
I sadly have no better idea how to solve the problem than to suggest syncing the master branch of your fork with wmde master (by simply replacing your master with ours). Sorry for the confusion we made by squashing the commits.

I am not sure how clear and helpful the above is. It seems quite chaotic at least. If you preferred to have more interactive attempt to fix the problems with your fork, I would be happy to try this out, e.g. on IRC. I am around wikimedia IRC channels (e.g. #wikimedia-dev) as "leszek_wmde", generally during European day time.

**Comment by tobijat** [comment]
@ivanhercaz so, the current state (master branch) of our repo is now deployed at https://lizenzhinweisgenerator.de/?lang=es
Best would be, you check on the page what still needs to change and open a fresh pull request with the remaining changes.

Thanks a lot for your effort!

**Comment by ivanhercaz** [comment]
@manicki, don't worry by the squashing commits. I understand what you have explained to me. In fact, the error was mine. I should had make a <code>git pull</code> from the master branch before to make my pull request to your master branch.

So, I am going to close this pull request, update my fork, make the necessary changes and then open a fresh pull request as @tobijat suggested to me.

Thanks to both for your effort! 

Regards, Iván

**Pull request closed without merging**
