### PR TITLE
Translation to Portuguese

### PR DESCRIPTION
**Pull request by Santamarcanda**
Hello everyone!

I finally translated all the files to Portuguese, as I told to Katja.  This is my first time working with GitHub, so I hope that everything will be correct. The translation **is not adapted to the Portuguese law**, Katja already knows it.

Any problem with the translation, notice me and I will try to fix it.

Regards, Santamarcanda

### CODE REVIEW

**Comment by manicki** [comment]
Thanks a lot @Santamarcanda!
I checked out the code and it looks good! I don't speak Portuguese but I trust you with the translation part :) Tehcnically all fine. Thanks!

One thing that I've spotted is that on "tabs" below the attribution box (on the final screen) there is still "Text", "Plain Text", "HTML". I guess  is not necessarily a super correct Portuguese but I can also imagine in this context it works well, that's why you did not change it.
In case you wanted to change this, it could always be done later.

**Comment by manicki** [comment]
Translation now live on: https://www.lizenzhinweisgenerator.de/?lang=pt
Thanks!

**Comment by Santamarcanda** [comment]
You're welcome @manicki!

About the tabs with «Text», «Plain Text» and «HTML», I didn't find this text strings in the <code>/i18n/es/i18n.js</code> that I use to translate to Portuguese. I have review again, not only the Spanish translation, German and English too, but I didn't find it either. Then, I check the JavaScript templates and I discovered that the three words aren't able to be translated, because they are written in the same template. In this case, [Attribution.handlebars](https://github.com/wmde/Lizenzhinweisgenerator/blob/master/js/app/templates/Attribution.handlebars). I checked the other languages in the website and in all is in English, even in German and Spanish.

If you make it translatable, I will translate as soon as possible!

Regards, Santamarcanda

**Comment by KatjaUllrich** [comment]
I am so happy it's finally here! I will give everything to the Portuguese lawyer next week. Thank you so very much @Santamarcanda !

**Pull request merged**
